### ISSUE TITLE
How to replace 'enc.encode(raw_text)' ?

### ISSUE THREAD

**Issue by soneo1127** [openai/gpt-2#104]
I want to use another tokenizer. I know the 'encoder.json' and 'vocab.bpe' are provided, but I can't understand how they are made.

How can I replace the tokenizer model to that I trained using own dataset.

Thanks.

**Comment by rkfg** [comment]
[Here's an example](https://github.com/rkfg/gpt-2/blob/fromscratch/src/encoder_sp.py). It's sufficient to change the import in other files to `import encoder_sp as encoder` after that.

**Comment by WuTheFWasThat** [comment]
You can read about the algorithm at https://en.wikipedia.org/wiki/Byte_pair_encoding and see some of our specific choices at https://github.com/openai/gpt-2/blob/master/src/encoder.py.  we haven't released the code for doing the counting/merges but it's (hopefully) not too bad!
