### ISSUE TITLE
If word2vec wasn't used, what was ?

### ISSUE THREAD

**Issue by bladedsupernova** [openai/gpt-2#105]
Word2vec and WordNet can translate words, like cat=dog. They can create a high dimensional relational-clustering in a neural network.

French to English - yous do translation. And, when GPT-2 very-accurately predicts the next word, it looks at all the last words - various needs for translation come into play, absolutely.

And, GPT-2's translation is superb clearly. 

But how does GPT-2 know cat=dog!? What did yous use? Why is it so good?

**Comment by WuTheFWasThat** [comment]
GPT-2's translation ability is not particularly great compared to state of the art systems.  

Regarding your question, you can read about the Transformer architecture online (paper is https://arxiv.org/abs/1706.03762).
