### ISSUE TITLE
How can I use this for sentiment analysis task?

### ISSUE THREAD

**Issue by ViswanathaReddyGajjala** [openai/gpt-2#109]

**Comment by huseinzol05** [comment]
https://github.com/huseinzol05/NLP-Models-Tensorflow/blob/master/text-classification/65.gpt-2.ipynb

**Comment by bhoomit** [comment]
> https://github.com/huseinzol05/NLP-Models-Tensorflow/blob/master/text-classification/65.gpt-2.ipynb

Where does it download pre-trained model?

**Comment by ViswanathaReddyGajjala** [comment]
I think it's just an implementation of the architecture of the GTP-2.
