### ISSUE TITLE
Reading Comprehension: answer questions about given passages 

### ISSUE THREAD

**Issue by syedmustafa54** [openai/gpt-2#112]
Is there any way to run the Reading Comprehension: answer questions about given passages as shown in the openai example [link](https://openai.com/blog/better-language-models/#task1). 
Can we run this using 117m model if yes than how.

**Comment by WuTheFWasThat** [comment]
Yes, it should be very straightforward - you'd sample from a context constructed just like in the link.  Unfortunately we haven't released code specifically for this, but it's relatively easy to figure out for someone with some experience with these things!

**Comment by AdamSpannbauer** [comment]
@syedmustafa54 (and any future readers that end up here like me).

I was also curious to reproduce the reading comprehension portion of the linked blog post.  Below are the steps I took to reproduce.

* Made script that is a variation of `interactive_conditional_samples.py` that accepts text input in the form of a text file (see [`file_input_conditional_samples.py`](https://github.com/AdamSpannbauer/gpt-2/blob/master/src/file_input_conditional_samples.py)).
* Placed the text from the blog post in the text file to be used as input (see [`input_text.txt`](https://github.com/AdamSpannbauer/gpt-2/blob/master/input_text.txt)).
* Ran the below command to get the below output.  I originally ran with `seed=42` and no restriction on `length`; I set `length=2` after I saw this produced the desired result.

###### Command
```bash
python src/file_input_conditional_samples.py input_text.txt --seed 42 --length 2
```

###### Output
```
======================================== SAMPLE 1 ========================================
 Mount Everest
================================================================================
```

**Comment by syedmustafa54** [comment]
Thanks for the reply @AdamSpannbauer I was waiting for someone like you. I will try this and let you know

**Comment by gionapaolini** [comment]
> @syedmustafa54 (and any future readers that end up here like me).
> 
> I was also curious to reproduce the reading comprehension portion of the linked blog post. Below are the steps I took to reproduce.
> 
> * Made script that is a variation of `interactive_conditional_samples.py` that accepts text input in the form of a text file (see [`file_input_conditional_samples.py`](https://github.com/AdamSpannbauer/gpt-2/blob/master/src/file_input_conditional_samples.py)).
> * Placed the text from the blog post in the text file to be used as input (see [`input_text.txt`](https://github.com/AdamSpannbauer/gpt-2/blob/master/input_text.txt)).
> * Ran the below command to get the below output.  I originally ran with `seed=42` and no restriction on `length`; I set `length=2` after I saw this produced the desired result.
> 
> ###### Command
> ```shell
> python src/file_input_conditional_samples.py input_text.txt --seed 42 --length 2
> ```
> 
> ###### Output
> ```
> ======================================== SAMPLE 1 ========================================
>  Mount Everest
> ================================================================================
> ```

I get a different output, what is your config exactly?
Below is what I used:

 ###### Config
```
def interact_model(
    input_file = "input_text.txt",
    model_name="117M",
    seed=42,
    nsamples=1,
    batch_size=1,
    length=2,
    temperature=1,
    top_k=0,
):
```
###### Output
```
======================================== SAMPLE 1 ========================================
 Just one
================================================================================
```

**Comment by AdamSpannbauer** [comment]
My output was generated by the below command. The contents of `file_input_conditional_samples.py` when I ran the command were exactly as they are in my repo. 

###### Command
```bash
python src/file_input_conditional_samples.py input_text.txt --seed 42 --length 2
```

**Comment by syedmustafa54** [comment]
@AdamSpannbauer  I am also getting the same output as @gionapaolini 
I have run the same command 
`python src/file_input_conditional_samples.py input_text.txt --seed 42 --length 2`
output is 
`======================================== SAMPLE 1 ========================================
 Just one
================================================================================`

when I change the `input_text.txt` question from 
`Q: And did they climb any mountains?`
to
`Q: what was the mountain they climbed?`
I am getting the output 
`======================================== SAMPLE 1 ========================================
 Everest
================================================================================`

**Comment by marciopuga** [comment]
I've got correct answers here by removing `length` and setting `top_k` to 1

**Comment by azizullah2017** [comment]
to get the same resutls as @AdamSpannbauer, use his forked [code](https://github.com/AdamSpannbauer/gpt-2/)
```
 python src/file_input_conditional_samples.py input_text.txt --seed 42 --length 2
======================================== SAMPLE 1 ========================================
 Mount Everest
================================================================================
```
```
numpy==1.16.4
tensorflow==1.14.0
```
