### ISSUE TITLE
Create and fit my own vocab.bpe

### ISSUE THREAD

**Issue by rafaelmg07** [openai/gpt-2#114]
Hello. First of all, thank you so much for this great job and for sharing with the community. 

I would like to know how I could create my own vocab.bpe file. I have a spanish corpus text that I would like to use to fit my own bpe encoder. I have succeedeed in creating the encoder.json with the [python-bpe](https://github.com/soaxelbrooke/python-bpe) library, but I have no idea on how to obtain the vocab.bpe file. 

I have reviewed the code in encoder.py but, I have not been able to find any hint. Any help or idea?

Thank you so much in advance

**Comment by 8enmann** [comment]
Consider https://github.com/google/sentencepiece

**Comment by ZheMann** [comment]
@rafaelmg07  I'm trying to do the same thing for the Dutch language, so I'm wondering if you found anything useful w.r.t. obtain the vocab.bpe file?

**Comment by raulpuric** [comment]
I think vocab.bpe should be consistent across vocabulary. 
vocab.bpe is the vocab that specifies byte merges/byte encoding. 
Maybe I'm wrong, but I think the byte merges should be agnostic across language and corpora.

**Comment by WuTheFWasThat** [comment]
see https://github.com/openai/gpt-2/issues/104

**Comment by zendevil** [comment]
@8enmann, using sentencepiece generates filename.model, but filename.model has certain non-utf-8 characters in it that throw an error when read.
