### ISSUE TITLE
Simple common questions lurking

### ISSUE THREAD

**Issue by bladedsupernova** [openai/gpt-2#116]
0) Do yous really know how it works or is there [some] black-box mystery?

1) What is the closest thing to GPT-2? BERT? Or simply the Transformer? But how close is it?

2) Byte Pair Encoding discovers segmented parse parts like this?: [[The [red ball]] [hit [the ground]]]

3) Say we have a 200-word book and want to predict the next word. Do you place multi-head windows along the end like this and then sum em together? Three 4-word windows are below:

... and so the frog and [cat (lived {happily ever] after) because}

4) In the net, do yous sum the created window with the positional BPE to get compatible decision for next word?

5) Dispensing terminology, summarizing GPT-2 greatly, explain how GPT-2 predicts the next word, how does it know what follows? How many words are actually looked at? Where? Does it refine its decision? If it seen the word follow before, what else is there to it...It's like a markov chain.
-------------------------------------------------------------------------------------------------
...I really want to see it drawn full detail, I don't know all this vector norm dot product language, I want it in English...

**Comment by WuTheFWasThat** [comment]
sorry, this isn't the right place for these questions!
