### ISSUE TITLE
Looking for a GPT-2 diagram

### ISSUE THREAD

**Issue by bladedsupernova** [openai/gpt-2#117]
I'd take this as a code 'issue'. (not actually the code part, but the math & terminology)

I'm not a layman - I do work too hard on AGI, but I (laymen figure in too) have taken the path to become fully experienced in AGI with no code or math whatsoever... Don't laugh, it worked.

I want to learn from GPT-2 immediately, as I have a white-box net made of contexts that can do everything, so I want to see a few things...

Issue is the algorithm is advanced, the matrices/Norm/etc (ignore code) 'flow' is not explained, I need a flowing diagram that goes further than any currently on the internet and shows these math/layer-terms. I need to move fast...

I'm looking to pay someone.

While I have to hire programmers to build my stuff, the real issue is not knowing 'what' to tell them to code...the AI 'idea' comes first, and I'm really good at that part.

-------------------------------------------------

The takeaway here is I have a lot of effort to put in and make huge change immediately to make AGI, worth 50 brains of effort in a year, but I need some help here.... Too few freelancers even know this new area of BERT & GPT-2.

**Comment by spacewalkingninja** [comment]
hey bladedsupernova, would love to get in contact with you!

**Comment by cryptomonopoly** [comment]
can you help me with GPT-2?
