### ISSUE TITLE
What are the 117M parameters?

### ISSUE THREAD

**Issue by leestar** [openai/gpt-2#118]
Trying to understand what is meant by "parameters" in this context, but could not find this anywhere in the literature. Are these attention scores for each word in the transformer? How does a larger amount of parameters help the model accuracy?

Also, given that this is Transformer-based, is there an easy way to visualize these attention scores (ie, see which words the network attended to for each representation)?

**Comment by albertwujj** [comment]
As described in the architecture section of the Transformer paper and the first GPT paper, there are many fully-connected layers in the decoder architecture. I wrote a post concisely describing the GPT-2 architecture and the relevant terms from the Transformer paper: https://albertwujj.github.io/gpt2sampling/

**Comment by WuTheFWasThat** [comment]
You can search online for "neural network parameters".  They're also often called "weights".  It's possible to visualize the attention scores, yes!  See: https://towardsdatascience.com/openai-gpt-2-understanding-language-generation-through-visualization-8252f683b2f8 (also maybe of interest is https://openai.com/blog/sparse-transformer/)
