### ISSUE TITLE
Interested in programming length recognition.

### ISSUE THREAD

**Issue by SendingAFax** [openai/gpt-2#125]
Hello! I was wondering if you guys would be interested in collaborating on programming in a stop-word or length recognition to adjust the text output. (like dicing it instead of 3-4 paragraphs every time.)

Was this considered, and I was wondering if there was any harm in a PR to adjust the values for each text input. Like saying:

Input: The cat is blue
output: and brown and grey.

Instead of:
Input: The cat is blue
output: and brown and grey... 5 paragraphs.

**Comment by WuTheFWasThat** [comment]
we're not planning to update this repo much based on feature requests but feel free to fork it
