### ISSUE TITLE
Can't open download_model.sh in colab

### ISSUE THREAD

**Issue by qo4on** [openai/gpt-2#127]
When I try to download the model I see the error:

> sh: 0: Can't open download_model.sh

What am I doing wrong? I used this code in colab:
```
!git clone https://github.com/openai/gpt-2
%cd gpt-2
!sh download_model.sh 117M
import re
with open('requirements.txt', 'r+') as f:
  t = f.read()
  t = re.sub("regex==\d+\.\d+\.\d+", "regex==2018.01.10", t)
  f.seek(0)
  f.write(t)
!pip3 install -r requirements.txt
```

**Comment by WuTheFWasThat** [comment]
it's download_model.py now!

**Comment by qo4on** [comment]
Thank you. I tried to replase it with
`!sh download_model.py 117M`
But still have the error:

> download_model.py: 1: download_model.py: import: not foun

d

**Comment by WuTheFWasThat** [comment]
you're running a python script as a shell script i think... my guess is `!python download_model.py 117M`

**Comment by qo4on** [comment]
Thank you very much!
