### ISSUE TITLE
Why does GPT-2 use a 500MB model.ckpt txt file that contains Asian characters LOL?

### ISSUE THREAD

**Issue by bladedsupernova** [openai/gpt-2#132]
model.ckpt is almost 500MB in size for my download of GPT-2. Is this training data? Why the asian characters? How does GPT-2 USE this?

별ꠧ㰝噛빲࿆붣�㶣굑뵇ᦁ㸯䱝㶹甲밉ꬶ붨᷏붸手㹓㪚붒쑧㺏飩㷭뙲벧虧븽쁥㲚쉦㵒ᄃ봁హ㹞츙㸼㷑렊볕 㸀㶎뷻뵱㐄㶙訪브偱붤㴃둿㳆解㶔ͽ㱞餑부椨뵠㱏㶏⦱뷕伝뵋䁅㸉捺㴘鴆㸁벻蔺볯빱鐺범꿗봍☦븴಄뷆킔㸆윂㷕ᵜ봐횵㱊ᲁ㷘㗛㹶蘤뵅ꔲ뷄頱㸬끢㴂擄㸜㦞㸻㖨㸍ɳ㸄킹뷁봣ᰇ㸨겲뷆꯰㹺∼㷦暮븝쓏㹂⢻빯㸘븕뇈㷎史빇瓌벂쾼브붔也뷫ἶ믨�뺉ⶠ븩䫿뷝먮붛ꡌ븜䖏㶌꩘㸢륛뺅ఝ㮫홷㴃Ꝫ㹝뵆鼔㹢濟㷆쎪㶶鋈㸒쫜밲溝㯐﬒봈㳠븘邙㷞䉍빑캐㴏펿㱚ꂢ㴜℅붡㶓큠볥㶳郟㴿珌㴷⯄뷫⌁벂쫱봃ᦦ㶖붳잁뷰忿㷙쎧뷞༳㶧穀믘䭠븎齵븎軳볞�㶙ਜ믧ᕞ㲿㶿밲邝㴽툛븏茉뵑犚㷝新㲗♮봺㗾뷘儔㷶捴㱾㳺㷢ὕ븚狕㷮䦱㳞卦뷬㳦ᶀ봞Ꝼ㳲㵔将㶉夸㶻㷅븚㶒窲븘圄㷩檳㸉捯봉竂㸃维빂⃛㸥뺼뷪㲺취봕뢘븹盔븋ˮ붲⯠㭑é붳䥜㶟憱㸗㵋㭨㺇䧜뺗�뵼ꦀ븰ኪ㸛췪빋慌㹈௨뷳♂붝ื㶝玭㹛ꔯ㸾蹚㷌꽳뵈緁붙㭽벶܈㶕寛빯醢봼蘱㶸ꁊ뺇뷇驃㴊㷋鋹㶢૬붴ꚟ븃ᴶ빲减밋֗㷉敦봿唺㷷㣄㰃엓봉伟빓斫븅냿㴙❋벏뱐ছ뭫뵚櫅㶆丌㷸鼌뷦㶈ෞ뭙而㶏ⵓ븨뷛洄빏�㪡Ȭ븟햩㷸�㷟ꮓ봼᭴뵯콏뷗붭玖㰳귡㶣೜뷤ᖟ붉䋓븤璶벛犀뷣낥㷲볫嗷비ﭓ붵껺봥胒㷼斛봥Ḅ뷈봊꾢븞ꄯ㶍皀㶹捴벯ﮎ㷚腑㺁䄂㸙項㶍到㞳픧㶁鳠㸿ᇯ븗봪脚㵨㶎铙㷑༂㷥싐㲶皠붤ೢ븪ው㷻㸮Ⓛ㳵痂붔후㰓껬븜궱볃糄㷦㞔㹒뷵ᔁ벟稯믑八㱢ἡ봰렝㴅ਨ㴁췏㸷℉빨荟붼혴㵻❋빜鸾봾빯韇㹯ᣔ㹪劮뷪䔼배뵳グ붌砼뵭ⴀ㸚�㸃㷄ᑉ㷂捙㸼튆㶗�박㸊㲲⨷㸲無볷䁅㴛թ㺐퀱㯲鎌㸐ꇕ봀餉볤볙붓ၶ빙ꇩ븑뺃ᤩ㩎І뵏䓅㺆䛟㴑꘸㺁끹㸝哃붉遲㯴◫붢蕽㰑鉣붑괻븃㴶墧븽⋾붖厬㷲䘦㴓ﹿ㸇䈹붇㸆㵸᧨㹀䧤㷫e㮓䒩뱋㖩뷬ᬝ㵓鹴붯灩뺝줠㸱淵부뵜㡻㶛㣎㴝ꥨ㷱艳㶈㔇븲駖븷㶅ઌ붔䷘뷜唯빉灾㺁뎋뵸殨븧쓠㺨뷧⮳뵔툒붯鍭㴪핁㸤㵙�벶㷮镪봿烉㹂㺬붽�븢₰믪궔붕핚봔퍢뵎짲㲂⼹㶎薪㵾᮸벺䄗뵮㷏㸐髞㸲흌㵣ಥ붍箧밉鄖㵝ᡧ법喗㴡豮㳕ⷤ㴀䯹뱟☬㴾䤚븀픱㴔쎮붬砡븨དྷ밬彚븴뜃븉ⶎ빑葝붢紉븻ᕁ㶪淡㸊솝㷀뱒㲀䞹㸑橣㳹幍몀⦧㴣䴆㵸絲븬뮯㹂㌯븿皫㷰䒦븖檉㸴퍉봗묤붬ꜷ봔苚붱쳂볝ຓ㸺瘄벚㏲㶒త㴦軨부㗇㶓≱벗붢㸗봌㕙봎䟷뺦劺㴅䊾붢♀붽㲴뭈❽㳦䧆㳫ጾ뷠뺥㷍ꦤ봸嗒㷏䍩뵻毁㷉ﬡ물窹㺼뾟㬓붹썖붿뷀녃㸓鴓븛澹붣ჼ빠㌬㶱簤므ꟙ㶠ᰬ㹺襊붒�㵾ᤎ㵫邑㶛짚뵛┚㴬炚뱅ᶫ볅逃㹱뺋ၴ㵃ẇ붐쮫뷢К㱉൛㲕旕㱩뷃᪐㶰ꬳ㱗ᆓ㶑▙㷽邶븴蟆㺚႒㴍謂㳸볧瑂뺓潢㴮㴗㎛빟煉㯃ꀤ뷖朴㸬螆빔絷빪↧뱃㴿ᶊ㸂징빺翝븶꥙븴Ⱙ㴫䏽벿琘븎렭㴁飬㺧ˮ믫آ㮫纹뺂㷄밗㠺㴘빈匩붎ᚍ㸓攣㶂ꤶ볞㞻붉䴵붹붸ʒ㳘귂뷝잧붕ၷ㶗틈㵓臞㳔獶㷮著뵌㷝䅻㶢忙뮱鳠붨〿봤븍㶛㺜붖㸪Ꮿ㳇膩붍䯟㱃謺㱚笲벓꽱㲸⋒붴沆뷗⨭㴜禯밥␲뱻욁뷫좤뵧칕븛㬡❲㹅땳붐䦪㴐߅㯚⼏봕붼轝㶼≽벪㴝㶉뷅봰ꩯ빈ꄕ뵄ꄱ볨춆㶗⏋㵟冶㫜諧㪚⢤뱓龳밻頖뷴�븊髵븧�㳸䚻봣ࣗ븧ꧢ㱣嶪㴋㿆㺣䊵븘�㳽慩㺁줞붥蔟볛邰㹔ピ뷌쟏븿虝뷊ՠ븭ᓕ밮�붐笉㵣俜밃ꕜ㲮⃋㰂瘗븱褤㵪ꦪ봕�뵗쨾㳴⧬㴅ࣝ㷘鋼㵶븫㺕㵫暱㸥䫼뷛땨빂췺븚燛㸟ﶎ㸶뤚㶍㣕㶫摋㶐篃붦㖑㰮의㸚㶪븉뺁ﴃ븴硎븕螸㳍ഝ붲ὺ빅侖봕眶븧媺㷘ᐇ븨敨㸢嫇㵚ﰥ㴏虱㷶㶤洏뷣薻뷰麋㶈篰븾�뷝댣㨸ᛎ㺙脋봜䵠㶵횘뵫럘㸏ㆾ뺜弖봼ﳨ뷝询붧婴㸤뤰븉᳒뷱봢椗븽&븟첃㸃匁㶤췈㵫乆㸀뵐뷜訡붮�㹨㷨쇁빜ﳃ붠밡㵖䙾뱔ₛ믈㰐뷢蠽㺱㴼齊㯵霙㸈荭븊㸛꽲붒⿜㶦圗뷓⼓뵚묧㱃致㶜ᆏ븋戄봦孫㸆ឍ㸚�㶈籔㷕뱎�뮑脬븤➮㺑蹀㲫᣿㲙쪲뱰�㷾艎㱺ᙈ㴉捝㷳ᰇ봐덜뷠놇붣뢻㶆鰖븪詛붗ጶ㶆뵚띃㷣㶹撠븅Ჳ붧〞뺼娊㷠攖㺁纙봊⣯뷱욹뷮�뵼ᥒ㺝懒㸬盋㲟뵤釐븑븂鬦㷢쪏㸳ᤧ㶪Ѭ㲄咘㷖㔟㸡ꨵ㶨豯㵼㺎⧣㸐ﶚ븷�㶸�뺬ࣹ빆鞲㶲㴜坸븘鍿㲘ᅾ㲰ඤ㺇쑂뱌黡뵂賾㭑暑붏呋㺮趨㸣跔뵸쀘붉빦㹩聢㸙빨�㶯匡불꼿㯑㶸樝빧儵㸫낺㵖癋㹀튗뷕牂븯殞빗㬘㺫癪㴂腚㺬啠붡ߦ벙미ҍ븞蝲변笼붌헁㹴浑븀�㷤꘎㸜멀븟ⶕ㸺邁㬈绅㹋숊뱳㷞뵰⮾봜뷂뤎뷌䘶봳ᬧ㺑㷵⪥㻈欄븻怚봾䕯㴫歬㶙㦁㻄꩒뷟๹뷽猪믜핚㴤빂塑㸳⬂㲺誨㶲뷄훳㳈仆㳓辥봌镆㶋輨뷷◛빇웉㶊窳㸖출㸡㵫ጷ밞榟븝졤㷠恣㵸핊뵺迿㹁ꓱ븕髚㱔檌분䅔㹠ᮌ㶝Ϛ㸰뵟褿㴲릳붮鰄㲪趬븂�봨ꌇ벰롥붠陷뫽坬㷷䆑븒毭븝欃㵵㢕볪璘봃돟㺅剸㴤⼂붷륱븾댓㶧翠㸸ܶ㹄㉫뮼腏㴘辮붎㚶㲈ﺹ㴽ୱ븈ꩭ붺꼁봟㸙턨㴮挳㷧瑌㸚埜벐㒚뷡뱢봓덢㪯脕붩玔㷗옺붣ᦥ븫ௌ붼鱩븬藍뵽⇯㸒붉㴮銎뵭亢븄ꮾ뵍꺻부ᮏ봦辁믨쏼㸳뀗밃索㶠ⴞ㶛⿱㺗蒚㸜뽍㸢᠎뭔�믮젵㸀⸐㶻䲝붶糞㶎㸂싽㲏嗹㹔ꏬ㷚⢌㵀裹뮯ĩ붂䫜㹗鼜㸄Ŕ㵮㮨㸍읹뷣亏㶉ㄉ붐鐱벛箕뵓ᰳ㸁諼㻖뻖︇붚˅㸸῵㵃뷂堔㶰蔤㹼㳄붍뎡봰㓰뷷틛븲봚쥂붗弞㸾눲붟挓벃笏㶢쇲㳟㾑㸂�㲨ധ㸭甓봮绸㺊欦㮁꣈㳢ᕚ㶰㜈㸃磫㶓墋㸚Ჸ붶尷㹧�㵢䭯㷻禥봘䈚㸾黭봗䷆볪ꘖ뺅�뷂ᗒ㺆㮔븓⭢북꣑븨熧㰞﹩뷴㮔퍁뷀鰋㱤窪븗桙븄뷧敆㷵�㸠㙄㷃筶㴌㶀컝㷚귶㷪婬불謺㶵짽붽摏붛굹붒駦㷑쑗뺓ᚘ㹎廝㸅홡뱥ȿ빌幽뱧✱㴟絅빤֊㶚웳빖㣹빁鐂뺬陵뵇烱밞躟㴫ᐍ㳾⅘㶽紻㺚㸮᧦분ሡ㺕ꏸ㶔ۨ㫸죸㶄Ṫ븳ﲙ㴼쑷㵇掔뷤퓟붤캱뷍揜㸣嚙㹗汓뷩隈빥㪟㺳㊎㵝汜㸀뀮㺸♁㸌밂渫벇畛㬅㹀餬㶬燩븾뵃ဨ뷳⢧㹚姗㸰셾㶺斢븛㸄骖븝Ხ㲱�㶰炿빈˟㳭�㺎䥬㺨鍪㹹馑㸃髢릾빰騱㶈㶈줲㹶条㷀䩢㹻譶㲼䣨㹫覆㺇ᇔ뵎⍨븀뭷㰋틙붎䑔㸩㙴븝솶㺣箿뵜㪀㶬ᇌ봰眮㶽봥溴㸶쵵㻀魡봶븚䰜㶍鍾㶯튻뷰ẩ㹒跰㰺㿼뻐㊬벍㠝봳뒩㱭镰㸤笠㴚蠫봧분㳙唾㵑蓡㷎鞺㸫㙷㴈퀓㶫暓믒㷏㺁⟧㺑᱿㱻셅뭉밵붟䘺븘栴㶺軄㺈㵳늴붃炻㹬붛ᯎ븟퇵벂뺃弥붼໚㸅㸋ꍍ뵍㏾㸛訳㷉胯㯉᠓㷖ⅷ㸒貋㶥놎뷊送빰墷벏鞐㴐웮벓冉㷥쉥㶄반㯸곸㲼❐㸻걢㸘뉤㹫ꈬ뭢쭐㷶쀋뤓琨㵑ꯧ뷄ꋔ봖좇㱬ᤘ㶾볭㹙솫㶂䨼㶹㭒벐틡㵅빱㴀嘢붻⯟볓것뵱歮㶛氺㴔㓓뷎빡涨㮉隟㺓㶵䨸㶷␴㹤牘뵜䛄빽ꪮ㶽䪐병ӧ㸝뜜뮯붕᪖뵌쵥㹞莮㷦릹붲ꭰ뷨誯봗怵뱩辍㶄ᕂ㸁붒韷㷫䢿㰮㍵벸ߞ먿䩅㸯䫀븸ป㷵牲븫㸍ቄ㶈᥷븴臌㲿覬봡혝붧뷰糮붕ᶻ벓ꛤ뵻瑕㶉첟㹗�븰櫴㹈�뷙⽁뷦뼪㷯ﶞ㳇甖㹉瞚㵛ᩇ봫잪붑ঈ㷵↪빺Ƙ빉輇뵓寅㰫鍥㺁㷖䁸㶌깐㵁뾫붗䘁뷹鎵㹆첷㷏�뷝➪㴩䵓뷲郿븏ꯧ봡�뷷鸕㴎﹍㶃ᬿ븣몼빒凅븿ヱ㸿䀶㵋ꧡ붺␵㸚㶆騷㹀펆㶕ꐺ㻟떢㸦舉㴭鮱븿狽㷌ច㮿㴋㹴說빖䦻븎뀊븝⢫㴤㣼붟㷥䐻㲓耪㶐㧦븳㋨뮃䄺㳾ᙨ㵀軷㸔쒛㹼謱밀ႌ㲀浃뵕䗑㸛薳㸼偫㹨ᄎ뵓繞붝尅벻㨰뺁柸㹆阽봒䭳㶴儡㸗㷔ῐ붋䩽㺐㤏㴍퉭㹨ဨ㶲輞㸲봜⧜㴩꓇붥ﹾ뺃钅붘⑜㲎䀈빸㵛뵐૵㱕㲍먷븃빫㷯≔먓퐇뷉揓㸌抹㲘蠍㵊圇㶞㹿௻㸶阾부ᥠ뺈㷜봘놁븢攟㶫罺붚왈븁ᤲ븐Ἶ분㋁뮒客븅֯㺂㙂㵁玖㷁맢브ㄻ㶐뙲붻뽄뵶癋봭ꢁ㶦旸㸞錩㸖붙⋳㸆豈㸪妾븍㭖㸅㹚᪇㷚淏㸥⟍븤㸔ᢓ뷻㵿䜟㸨뙘볖﫶㵡㵡붬衤㸐㴸䯔붒�뷰먪㵺泃봺鎔붝篶뵐劗븶⎄㱶㸂欴㷉僄㵾챜뵰�뺪킌㶹浂㶦嫷㴕㝆붉늻㮰쨋㴬簁붯쇖㸬乮뵫b붆髦봱䢩볣ꤱ뻌誌볻禑뺙眇뱃揗㸧쿠뷒蔆㷷븒ꙷ뵴啬㷘͆㶷囉뷦뺁挵볾☝㲏㶁찀㵔⃢븛腾븹隶빚뇁봳蠛뺔ک㷞㶣갅㶮꧰밣誜㷁ﳽ븀䭴뷽ු빝噽븩আ블붵㊁봆혟붴꽜㶿ㄿ㱌칵뵘顝뷋⑞㵔�㹭㇐봉欀뷇㸤ⓐ뺂傖㶃㜫붺녽벧ᒑ뷕勧붨맸뷇�뷥Ṷ㲂䐀㹸벮賢밖᫩뱃㩏㷼㝇밫眮㵿囥㳤븮뮗㸇ઁ㹰짭㳍﫵봠⠧㯶롡㳲㹊찢묏뢮㱇老㴶橈㶩뭣㲦�㵷鮎뫞哲붩ꗶ㹋弦붳资㶒蒜볶㹛㦮볅뷮ꯂ㹒짒㴵䂦㸝᪏㷃﫪㹕ړ비揺뷊㋍뺴㳓㷜ჱ㸊ꇵ븊Ⓩ㹼搤㸺북퇳뷻滘뵯兀붻㶊ￔ㷥൷빛ꬍ㹑㾔븚踑뷤竂뱒ٙ㸤붻㑵붊厬뷞䄌먛렵봻ᴧ㷬蜔빀㲮됳㹊ḉ밿峂뷂橃뱥皠빊죞빓ꥬ빪붃⎮뱰蛫븤仔㬪枤봆끠㶏㳇흢㴤존㰮軐븩뻧빨㲼㳥Ṃ붍〨붤膝붭ᛍ븛㴻Ѣ벗娐븖㒘봎ﲡ벡鯠㸂왻㷳甿뫄➘㲡♂㴦艓벙欺봄莤붃汍벒駿뷀뵿ﱄ㸤版㵑䁪㯓濗붙�뵑刳㵞붋멠㶽血㷙棢㷡琭빻Ѝ㶐瘼븸㠾붙ᓫ㵒좴㷃봙뷌붨�북曑㪡颾㸣묧㺤쟓㸪᳙㲉⣟㰼⾢븯䁄밲콇㲓ণ㶡ꂩ빿ፉ㲑�㴒榁붭狶붦﨩㷈埿붙븎㟭뺏詡벓棛㴟妷뵙籍뵱蚶㸠Ꮙ㶧㸠抗봫됖뷅峝붎捘㸍嵅뷬鍄법嶯㶺䴤빩뱶硥봻숅㵊癃븟�봛ઌ붍⧛보鬇㴐介뷟㒎봯坓뷤ⱷ㸼䱒뵮縜㵩뵙Ø뷟퉾봓ᚈ봿ጃ뺣뫼븏樓㶑⋁븓䰝㷓삛㰈㵪㷘贼뷵쁙뺁�㱶勃㹁輁㷂菪㲂픷봉ꁣ뷌៍㱕㶈ᚽ븸朰빞賞벾굣븗럒붑黔㳵븚鐺븛謶㷥鰨븳瑻㷅뒮뱀㓧㳰븺诿㷱팔봇䉬븳뷺繰㺑㵙㗔봠វ㵔՗㵵ৌ붮ࡉ붅兀뵞僇㱎໕븞묣봣䰃븼텇㷁쩈㷠뵭툱봅怿㷡螸봒㼥븓웓뺄捧㯸湰㵣釟㹵붰剙㱶ꩪ㷫閕㳷⿾뵨㪊붸륷㸒촙뷀뺍㶉뵅ួ봴殝뵎ở뵀㷥胴㶭㸑ᣑ㶛赹㶛蛳㳨ᮧ봫䲲빀଍붯룲볐�빌ᅏ붱ऩ㳱禬㱦ꑺ볇よ㹁졽㶄잠빜ꮯ㷹᧻㬃�㶗␱㲁퍒빍䍂밓案㷝ᛃ㺂禲붧畤뵕쨆빹羜빅봝㜝㸹갥븖譿븘㺙㸶頞뺌䧧빋㓗밼䰶㵀單분㲎慿㶗노㵯ẝ㯆㴵뀩붶岣붓㹰䩻뻈᧍붶Ľ뺍㿳붒鄯붑뼜뷕杒붆㩰벨竛㴿肽빇慥붙罹㱱祍붇䍵㳰�븧禲빇㏇㶚貓㸏虋㸊鎾봞熤봲唙㶬䰟뵴蹹㶜痉븎鶣㺒ᕔ㵹腱㶔丕붮즽㴂늘병㴄ᄩ뷖洚븒ﴈ벓큲㶵컷㷋⪘빉郪볨䗏붯ﺣ㸔檥㷦�㷈봫䝐㲏ﰈ㸅ઞ뺏檭㶷䝲뷿헼㵓햍㷮嫟봁�뵐뼞볛眷부ﾚ㷘३㵉驒뷸⪥봛丗붚㑐㵿᪵뮜ਗ㷢㷝䋕㶞℟㹷쮺㳃ᅒ볜噒㱚춀㰯Ḍ㯸縠붷馴붎쑺볆ꒌ뷚⁹뷻羚㱀츱븈벅嵃뷄縸㷚썛비愭㴤؊빒뎣붪ꊤ뷮镟붥휪㹇睊븉歾븬빭퉈벘㬷붦ꉅ㴭㽫븙㤞㳫㶾㸁⪲뵨Ǐ㶧섦벺䛣㺝㶴�봳遝븛觴붫蔍㱉ꑇ붯甚㸀볾븾儞㶅菤붂㵣홃㷑趋㵅殽볓Ӡ㶖냡벰ﲉ불蛌볠ᦞ뺁ྴ㴣ꄡ붌渏㸕ਹ㷱䡿뷱⻳㷢﯏뷿᰺㩌蕤뵚븮뺟栧붲᱿㸎଺㷊ᙋ뷰唩뱩匁빔셝븛가㵺㷚顳㲸毇㳢ᨹ㵸ퟒ㯅蛸붍沈븵⇑뺪ﹹ㳇ȱ㷇쬛뭋婩벵揉㴡ꔱ뺅葋빻諬볯⓻㸃൝뺋汾㸔걑㶆᪕뷆법갊㳑䡨븝䧓㵈ᄙ뷀㰹븟뺅鰽㲳㏀㴲�㱘㴳칩붚彗뷅㬇봽뎭봶㷝㸬홰㰣뵒㴥⬟㴂㻵㷅ᚆ㹃˩부앟봒ꤖ㶫⇇붚貽㶫쏗밠롭벴뮂㰹ྈ벱ᳰ붃椝㹶綍봙髑볕䫲뷫Ц븈㹟澘별ॼ㳦姶븑㾤뱀빰縣봧Ⅻ붸涕㸒㿜붩颪㶖䰱뵏㟩㯆皋뺁老뺂迯㵅낥볋鶷뷼찕봼ᇩ뵳踲북炙뵣᱇㱠ⳓ㵌襥㲌�봫즈㶐ﺝ㸅᱾㲔뎗㷐틿㴖ꢠ뷇ፅ㯝뱎ᙂ붮允봷藫㸗炊㵘쨢㶄涰붫⠴뵾ه붥≤㷫㞡빜瘟붕१븒�봦饺븲⎌봕餫㸢㜏㰷杯뷤꽔붅ፖ볃쟃㶁돢㹉垚븯鋶뮐떈㲨鯯㺄ᆉ㸱靈㳵⸅붔㊸믵﹆븒場빈賠㷃㖢㸜巁붡軠븄꾸㶻�븲菾빸ﴮ빘蛝봎㇠㷯밵㴕︯먷궶먀劬뵏풑㴫뱳﯏㶸㯛㯽皿㸗豜븎嚴㶝天㴶㣇봙ꄛ뷬닑붕쯤㴧汹붚㳲븘⶞㲆꼉㷥銇봏໎백핫봂㺉뵀붂怍뷍ᩄ㴖룅㸞홯밃죭㸎暆밄閊븳ﹺ㶈䇭㺎ꖤ븬ᵡ빇휆븟�㳈㶝잻㺢뛉뷦時먃輻봇㫚뺠뷼붑埐㶨ୗ빡ᅏ㵏㬑㶌╓㰚餏㸗焯발⿱빘퇢㹃侌㳢빐㳟鷎뱚轂뱵式벐梅㴕鄛붙㶈匚㶱ᕋ㸪쳗붛㾇㵹᫱뱪࢈븏㭧兑뷲聳붗襨봾院봪穞봢퓉믨蕲㶱᩵뷫๻㩩篍㸉ꕅ㸈鑡㲜্밐땗뷠檔뷅㵣붏ﱂ법⺀빜Ⲱ빨ࡘ뺯砬븯䊬㷐ᖎ뷇나㹊墝㷄送봭븯믖㶸े㴶哣붐鯖봏�블ꚢ묢�㸮䛟㸑῱뷋ꎆ㵐ډ㲼有㶣꺑㸜쯔㶼ٱ㬒嬨빠娩볊콺㴁ｖ㯳ܘ㹀㹴얍㶃童백帢븅ꁬ븠ᣯ㶻朰벸ڡ빰䟮븐침㹍킠빓㷏冃볼诈뺵歂㶍痎붨놺㴚䜑㸜䒅믟뤻벯ॏ㴚糗㸐䷿㶻鴭뷺�㵐큕㸵鰴븃빆妅㶨샓㺑੃뵤㏹벾瀒㴮ꁢ㷈辰뺢柵붊ᾘ뷍酫㳚Ｋ붯빓븵붘ᗄ뷠ᯰ븞㿻㴢빕앿㸕穦븮갔빮￳봜໹㷂꘎븨ӗ㷜顺㰦睹붇⪚㸲ꖺ봝ી㳈╒㳷뀿붵䈍㵌

**Comment by deepbluesea** [comment]
unicode?

**Comment by WuTheFWasThat** [comment]
it's tensorflow's checkpoint format
