### ISSUE TITLE
ZeroDivisionError: integer division or modulo by zero

### ISSUE THREAD

**Issue by Ceebox** [openai/gpt-2#164]
When I run my train.py, this is the output

Loading checkpoint models\117M\model.ckpt
W0802 09:08:48.051176  6828 deprecation.py:323] From C:\Program Files\Python36\lib\site-packages\tensorflow\python\training\saver.py:1276: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
Loading dataset...
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 1001.03it/s]
dataset has 0 tokens
Training...
Traceback (most recent call last):
  File "train.py", line 293, in <module>
    main()
  File "train.py", line 271, in main
    feed_dict={context: sample_batch()})
  File "train.py", line 247, in sample_batch
    return [data_sampler.sample(1024) for _ in range(args.batch_size)]
  File "train.py", line 247, in <listcomp>
    return [data_sampler.sample(1024) for _ in range(args.batch_size)]
  File "C:\Users\pc\Documents\.Random Programming\Ai Test\GPT-2\gpt-2-finetuning\src\load_dataset.py", line 74, in sample
    self.chunks
ZeroDivisionError: integer division or modulo by zero

My idea is that I may have too small of a dataset, but upon consistently increasing size, it is not to be. I have moved from 300 lines to 3100.
Help?

**Comment by Ceebox** [comment]
There was too little text. I upped my amount of text to 4000 and also made sure there was no double extension, eg lyric.txt.txt. It works now.

**Comment by s1072489** [comment]
This error happened when I did not have <|endoftext|> at the end of the file. (Text was less than 4000 lines)
