### ISSUE TITLE
conv1d naming?

### ISSUE THREAD

**Issue by ZeweiChu** [openai/gpt-2#165]
I am wondering why is this function https://github.com/openai/gpt-2/blob/master/src/model.py#L50 named conv1d? 

It seems to be a linear transformation to me, not a conv1d operation.

**Comment by WuTheFWasThat** [comment]
yeah, it could just be called linear.  since we're operating on sequences but acting independently on the sequence dimension, it can also be thought of as a conv with filter size 1, hence the name
