### ISSUE TITLE
Why not the 1.5B model as well? Even 8.3B (instructions) have been posted by NVIDIA

### ISSUE THREAD

**Issue by 4R7I5T** [openai/gpt-2#169]
Now as I understand, and have audited the code myself - NVIDIA has released an improved 8.3B solution, albeit not a MODEL - I was able to follow it through to the point that I fully understood what actually RUNNING this monstrosity would take in computing power and dollars considering I'd probably need to settle for cloud TPU through google or amazon. The cost was unappealing to say the least. 

Now we're already to the 755M model - THANK YOU! Don't think I'm not grateful. But it just makes sense to release the full 1.5B as most of your partners have said there is little difference between the two anyways, and smaller researchers who don't want to rack up a $3000 compute bill to train a model would love to have it. I understand this is actually probably the biggest "danger" you guys were referring to early on - certain people not having access to re-train the software. But at least having a point of reference helps us connect the dots. 

Thanks again.

**Comment by WuTheFWasThat** [comment]
dup https://github.com/openai/gpt-2/issues/16
