### ISSUE TITLE
Is there a plan to support PyTorch?

### ISSUE THREAD

**Issue by lemonhu** [openai/gpt-2#17]
Thanks for the awesome work, hope to support PyTorch.

**Comment by WuTheFWasThat** [comment]
sorry, we won't be officially supporting this but look out for others' forks!

**Comment by ethanjperez** [comment]
It looks like some are considering adding GPT-2 to Hugging Face's BERT repo: https://github.com/huggingface/pytorch-pretrained-BERT/issues/281

**Comment by lemonhu** [comment]
@WuTheFWasThat, tanks for your reply.
@ethanjperez, it is a good news for PyTorch users.
