### ISSUE TITLE
How to get reproducible interactive conditional samples?

### ISSUE THREAD

**Issue by gugray** [openai/gpt-2#172]
The 'seed' argument of interactive_conditional_samples.py helps getting reproducible sample if I restart the script, i.e., if I start from a new session.

However, I cannot find a way to get the exact same sample for the same prompt within a single session. How can this be achieved without creating a new session?

**Comment by WuTheFWasThat** [comment]
this is a limitation of tensorflow, i think.  you'd have to change the tf.multinomial call within sample to use stateless randomness or something like that
