### ISSUE TITLE
It is painful to install gsutil, why not wget/curl

### ISSUE THREAD

**Issue by lgpang** [openai/gpt-2#18]
As shown in title

**Comment by lgpang** [comment]
Even after installed, there are still many errors 

sh download_model.sh 
ServiceException: 401 Anonymous caller does not have storage.objects.get access to gpt-2/models//checkpoint.
ServiceException: 401 Anonymous caller does not have storage.objects.get access to gpt-2/models//encoder.json.
ServiceException: 401 Anonymous caller does not have storage.objects.get access to gpt-2/models//hparams.json.
ServiceException: 401 Anonymous caller does not have storage.objects.get access to gpt-2/models//model.ckpt.data-00000-of-00001.
ServiceException: 401 Anonymous caller does not have storage.objects.get access to gpt-2/models//model.ckpt.index.
ServiceException: 401 Anonymous caller does not have storage.objects.get access to gpt-2/models//model.ckpt.meta.
ServiceException: 401 Anonymous caller does not have storage.objects.get access to gpt-2/models//vocab.bpe.

**Comment by alfredcs** [comment]
Try to add 117M and see if it makes any difference.

**Comment by lopuhin** [comment]
> It is painful to install gsutil

`python2.7 -m pip install gsutil --user` worked for me

**Comment by dackdel** [comment]
running linux and having the same storage.objects.get error.

**Comment by lgpang** [comment]
Thanks all of you!
`python2.7 -m pip install gsutil --user `
and 
`sh download_model.sh 117M` 
works to install gsutil and download the pretrained model.
The tricky thing is that under linux gsutil only support python2.7 while I used 3.6.
And the **117M** is very important! I thought 117M means that this downloaded file will be 117M,
so did not include that in the beginning.

**Comment by nealmcb** [comment]
See [removed gsutil dependency by loretoparisi · Pull Request #21 · openai/gpt-2](https://github.com/openai/gpt-2/pull/21)

**Comment by shayakhmetov** [comment]
`pip2 install gsutil` worked for me

**Comment by ZeweiChu** [comment]
> gsutil cp gs://gpt-2/models/117M/encoder.json models/encoder.json
> INFO 0215 23:50:10.228441 retry_util.py] Retrying request, attempt #1...
> INFO 0215 23:51:11.842244 retry_util.py] Retrying request, attempt #2...
> INFO 0215 23:52:15.640549 retry_util.py] Retrying request, attempt #3...

For me it keeps retrying. Anyone knows why?

**Comment by WuTheFWasThat** [comment]
Sorry I don't have time to test right now but does something like this work?

`curl -X GET https://storage.googleapis.com/gpt-2/models/117M/encoder.json`

**Comment by studiosi** [comment]
Pull Request #39 takes care of this, I believe.

**Comment by WuTheFWasThat** [comment]
thanks!
