### ISSUE TITLE
Retraining with Beatles’ lyrics only

### ISSUE THREAD

**Issue by AndyObtiva** [openai/gpt-2#195]
Suppose I want a model of all Beetles’ lyrics, how do I train the system from scratch with them. Assume I have them in a txt file. What would be the steps? My goal is to input Beatles lyrics and then output new lyrics in the same style. Detailed answers or pointers are highly appreciated. 
I noticed this project is aiming to achieve "general" capabilities as opposed to "specialized" ones. If I am going about my problem the wrong way, or misunderstanding the premise of this project, please kindly correct me and provide pointers on how I'd achieve my goal elsewhere if possible.
Thank you.
-Andy

**Comment by AndyObtiva** [comment]
OK, I just noticed that when I run the conditional version "src/interactive_conditional_samples.py", I get a Model prompt. I entered part of a Beetles song lyrics there and got output in return. Perhaps that's all I was looking for. I'll keep tinkering with. It seems the point of your project is that I could just use one of the bigger models (like 774M) and not have to retrain myself. Either way, thank you very much for making this available. I am going to mark the issue closed, but if you have any feedback, you may re-open or add a comment anyways. Cheers. -Andy

**Comment by AmbiguousError** [comment]
Hi there, I have a model that I've trained on Beatles lyrics on the 345M model which I'm happy to share

**Comment by AndyObtiva** [comment]
Thanks a lot. Please share. Let me know if you need anything from me to do so. Cheers.

**Comment by AndyObtiva** [comment]
Btw, did you train model with Beatles lyrics on top of the original model or from scratch?

Is there a URL I can follow to download or a GitHub repository that contains it? (Unless you have a different way you prefer to share)

Thank you,

Andy

**Comment by senorblasto** [comment]
Despite having written many songs the entirety of Beatles lyrics would only fill a few pages and is an extremely small data set to use to fine tune.
  I've had some success using every William S. Burroughs text I could find, and the output clearly has his flavour of writing as an influence, but just one of his books is much larger than all the Beatles lyrics combined.
