### ISSUE TITLE
Translation task

### ISSUE THREAD

**Issue by djstrong** [openai/gpt-2#20]
What was the format for translation task?
Do you provide sequence of pairs delimited by new lines, e.g. "sentence1 = translation_of_sentence1 \n sentence2 = translation_of_sentence2 \n ... \n testing_sentence = "?
Does the training dataset consist of similar format translations?

**Comment by WuTheFWasThat** [comment]
format is correct!

RE training dataset - see paper for details!

**Comment by djstrong** [comment]
I have read the paper, my question is: the ability to provide translation for a sentence comes from training data (there were some texts with similar translation pair format) or something else?
In other words, if I take two totally monolingual corpora (English and French) and train your model, will be the translation working?

**Comment by marcoaleixo** [comment]
@djstrong any news about that?
