### ISSUE TITLE
Can't install sh_download_model.sh

### ISSUE THREAD

**Issue by FatElmo** [openai/gpt-2#22]
Noob here (linguist, with rudimentary knowledge of computers) I've installed the gcloud sdk but I can't get the command: _sh download_model.sh 117M_ to run. I get: 'sh' is not recognized as an internal or external command. 
Any help would be greatly appreciated.

**Comment by dackdel** [comment]
what operating system are you running? https://www.youtube.com/watch?v=0AiqegwnskE

**Comment by FloridaPete** [comment]
I'm using Windows, 64x and had the exact same error "sh is not recognized as an internal or external command."
I tried the linux path fix from dackdel, then received a different error when using the Google Cloud SDK shell: download_model.sh: download_model.sh: No such file or directory
Also tried running: gsutil cp -r dir gs://gpt-2/models/ models
But receive error: CommandException: No URLs matched: dir

**Comment by FatElmo** [comment]
> what operating system are you running? https://www.youtube.com/watch?v=0AiqegwnskE

Sorry Win 7 64x

**Comment by sra4077** [comment]
Hi, 
I get "AccessDeniedException: 403 <email address> does not have storage.objects.list access to gpt-2." on each of the objects in the list.
I'm running gsutil on Mac OS X 10.14.2 (Mojave) via the gcloud command line install path suggested by the gsutil_install link quoted in READMEmd.
Can you move the objects to here? It might make life easier for those who don't need to use the gcloud cli. Alternatively, can you allow the required access permissions to gpt-2?
Thanks

**Comment by sra4077** [comment]
Hi again,
While I was writing the above a notification came in with this in it:
"sh download_model.sh 117M"
adding the model name.

Thanks, that worked!

**Comment by FloridaPete** [comment]
Just to be clear, I was using exactly:
sh download_model.sh 117M
but still receive an error: download_model.sh: download_model.sh: No such file or directory

**Comment by studiosi** [comment]
try

`sh ./download_model.sh`

**Comment by xeb** [comment]
For those who are receiving a 403, I re-ran `gcloud init` and that did it. Strange because I already had a gcloud configuration set.

**Comment by minkles** [comment]
I'm getting "syntax error near unexpected token `do"

I'm running Mac OS X 10.14.2.

**Comment by loretoparisi** [comment]
There is not need of **gcloud** guys, you can just use this version I did that uses only **curl**

https://github.com/loretoparisi/gpt-2/blob/master/download_model.sh

**Comment by studiosi** [comment]
@loretoparisi apparently there is one on the queue that uses the publicly accesible storage API, #39

**Comment by WuTheFWasThat** [comment]
script should be better now and doesn't have gsutil dependency!

**Comment by loretoparisi** [comment]
@WuTheFWasThat finally!

**Comment by wac81** [comment]
https://drive.google.com/uc?export=download&id=1Eskens0NNz4a6WvqDuIB2tP3QMQ186BY

you can direct download

**Comment by loretoparisi** [comment]
@wac81 yes exactly, this is the solution I have proposed since gdrive for a given `id` has a direct download link. By the way you cannot use `curl` in every case given the file size, but in any case it's very easy (see above).
