### ISSUE TITLE
recommended VRAM for the small 117M model

### ISSUE THREAD

**Issue by Dampfinchen** [openai/gpt-2#226]
Hello,

is it possible to train the small 117M GPT-2 model with 6 GB VRAM using FP16?

Recommended Vram is 12 GB so with fp16 I could halve the memory consumption?

**Comment by sarthakmalik** [comment]
Certainly possible to finetune ``gpt2 small 117M`` parameter model with ``fp16`` and ``batch_size=256`` on CUDA capable cards with 6gb addressable memory space. 

For downstream model consumption, the overhead is smaller so it might even be possible to run containerized text generation workloads on cards like GRID M40s that have quad GM107 substrates with 4GB each.

```bash
$ py3 ../huggingface.transformers/run_language_generation.py "${props}"
...
[ device: Tesla M40 ]
Memory Usage: 4742 MiB / 12212 MiB
```

**Comment by Dampfinchen** [comment]
Thank you very much, that helps me a lot :)
