### ISSUE TITLE
Try in Colaboratory

### ISSUE THREAD

**Issue by phmb** [openai/gpt-2#25]
For a quick run:
https://colab.research.google.com/drive/1UfBDy-UkONgfdER21VNUCnsf63LGldFA

**Comment by nealmcb** [comment]
Awesome!  Very fast!  Especially compared to my old laptop :)

**Comment by WuTheFWasThat** [comment]
thanks!  very helpful, but i'm closing this as it's not an issue

**Comment by nealmcb** [comment]
I would suggest re-opening this as a request for an addition to the repo (e.g. the README) to offer collaboratory execution as an option. It would be a far easier way for folks to try the code out.
I don't know if this particular link is all we need, or if some sort of code changes would make it easy to make the latest version available in the collaboratory, of if the team should support something in an official collaboratory space.

**Comment by killerzula** [comment]
@phmb notebook is deprecated. For any future reference, use [this](https://colab.research.google.com/drive/1VgkQvRyE6rK7bxQO1VdPy57uBc9KI4Iu?usp=sharing) one instead.
