### ISSUE TITLE
download_model.py never gets requests

### ISSUE THREAD

**Issue by jamieChipscan** [openai/gpt-2#259]
Hi, I'm having an issue trying to use download_model.py to get any of the models. I've tried some debugging and it looks like the requests.get commands are never returning. When I manually navigate to the address in browser, it looks like the page contains no files/data. Have the locations of the models changed? This occurs for all 4 sets of model data.

**Comment by DaveXanatos** [comment]
What platform are you running?  Can you post the exact code of your copy of download_model.py?  Do you have the right model names for each model? (117M, 345M, 774M, 1558M)

I've successfully run this script now on several others' systems (although I smartly now copied all the models to a thumb drive and just manually drop them in when configuring for folks - saves MUCH time) - I'll be happy to help you get it running if I can.

**Comment by DaveXanatos** [comment]
Anybody home?

**Comment by jamieChipscan** [comment]
Yes, thank you. I used the exact download_model.py currently in the GitHub repo, and cycled through that list (117M, 345M...) but no luck for any. However, I remedied my problem by just downloading the docker image and manually extracting the model files from there with docker cp

**Comment by jamieChipscan** [comment]
Just tried running the py script again, and it found the requests this time! Not sure why they appeared to be temporarily unavailable. Possibly a network issue, closing this
