### ISSUE TITLE
Is there a way to use gpt-2 with the newest tensorflow (2.4)?

### ISSUE THREAD

**Issue by artiblaster** [openai/gpt-2#277]
I tried and it didn't work. 

I am having trouble installing tensorflow 1.12.0.

I am trying `pip3 install tensorflow==1.12.0`

Which returns:
`ERROR: Could not find a version that satisfies the requirement tensorflow==1.12.0 (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.2.1, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0, 2.3.1, 2.4.0rc0, 2.4.0rc1, 2.4.0rc2, 2.4.0rc3, 2.4.0rc4)
ERROR: No matching distribution found for tensorflow==1.12.0`

**Comment by DaveXanatos** [comment]
Here's the full response on how I got GPT-2 running with TF=1.13.1, on a Linux-based system.  If you're running Windows or Apple, might not help...

[Running GPT-2 with Tensorflow & 'GPT-2 Client'](https://www.reddit.com/r/BuildingWestworld/comments/hz42f7/running_gpt2_on_a_raspberry_pi_4_4g/)

Good luck!

**Comment by artiblaster** [comment]
> Here's the full response on how I got GPT-2 running with TF=1.13.1, on a Linux-based system. If you're running Windows or Apple, might not help...
> 
> [Running GPT-2 with Tensorflow & 'GPT-2 Client'](https://www.reddit.com/r/BuildingWestworld/comments/hz42f7/running_gpt2_on_a_raspberry_pi_4_4g/)
> 
> Good luck!

First i have to be able to install 1.13.1 or 1.12.0. How did you install 1.13.1?

**Comment by rMazeiks** [comment]
> ERROR: Could not find a version that satisfies the requirement tensorflow==1.12.0

I got a similar error when trying to install with Python 3.8. I managed to get GPT-2 to work with Python 3.5 and TF 1.14.0.

> First i have to be able to install 1.13.1 or 1.12.0

Version 1.12 will not work. Even though the instructions tell you to use 1.12, the scripts use features only available at later releases. For example, [tf.sort is used](https://github.com/openai/gpt-2/blob/master/src/sample.py#L28), which is [only available from v1.13](https://github.com/tensorflow/docs/blob/r1.13/site/en/api_docs/python/tf/sort.md). 

> Is there a way to use gpt-2 with the newest tensorflow (2.4)?

I haven't tried it myself, but you could take a look at https://github.com/akanyaani/gpt-2-tensorflow2.0

**Comment by artiblaster** [comment]
Thanks i'll try this!
