### ISSUE TITLE
Error with python download_model 117M

### ISSUE THREAD

**Issue by KabalanKeirouz** [openai/gpt-2#282]
https://storage.googleapis.com/gpt-2/models/117M/checkpoint
...
...
https://storage.googleapis.com/gpt-2/models/117M/vocab.bpe

<Error>
<Code>AccessDenied</Code>
<Message>Access denied.</Message>
<Details>Anonymous caller does not have storage.objects.get access to the Google Cloud Storage object.</Details>
</Error>

Getting this error, even when I visit the link normally from the browser.

**Comment by little512** [comment]
I'm also getting this error. There is a way to [make storage buckets public](https://cloud.google.com/storage/docs/access-control/making-data-public) if that would be a valid solution.

**Comment by little512** [comment]
@KabalanKeirouz I believe the issue has been fixed, I can download the 124M model using gpt-2-simple on Google Colab.

**Comment by KabalanKeirouz** [comment]
> @KabalanKeirouz I believe the issue has been fixed, I can download the 124M model using gpt-2-simple on Google Colab.

It did not work for me yet. When I run the download model script, it is still loading me with contents full of XML phrases with the same error message, and this is on google colab.

**Comment by Thomasbehan** [comment]
Moved to azure see the latest commit

**Comment by KabalanKeirouz** [comment]
I was requesting to the wrong url. Issue solved when copied download_model.py from openai github repo
