### ISSUE TITLE
WHEN I TRY TO TRAIN I GET THIS 

### ISSUE THREAD

**Issue by BigFatDecker** [openai/gpt-2#292]
Training...
Traceback (most recent call last):
  File "train.py", line 313, in <module>
    main()
  File "train.py", line 291, in main
    feed_dict={train_context: sample_batch()})
  File "train.py", line 267, in sample_batch
    return [data_sampler.sample(1024) for _ in range(args.batch_size)]
  File "train.py", line 267, in <listcomp>
    return [data_sampler.sample(1024) for _ in range(args.batch_size)]
  File "C:\Users\Nic\Documents\gpt-2\gpt-2\load_dataset.py", line 73, in sample
    assert length < self.total_size // len(
ZeroDivisionError: integer division or modulo by zero
i've sat here for over six hrs ive followed everything as closely as possible but just get error after error please help me

**Comment by BigFatDecker** [comment]
thanks for wasting my time with your broken ass code ive wasted my whole day with your stupid shit

**Comment by BigFatDecker** [comment]
fix youre stupid fucking code

**Comment by DaveXanatos** [comment]
And yet so many others have it working.  Perhaps your dataset is zero length?
