### ISSUE TITLE
vocab.bpe contains an invalid unicode char and can't be read in Windows

### ISSUE THREAD

**Issue by studiosi** [openai/gpt-2#30]
The reader causes an exception on Windows 10 when reading the vocab.bpe file. I have tried with Unix endlines and Windows endlines.

The byte that fails has a value of 0x81 and causes an exception when running the interactive mode.

**Comment by WuTheFWasThat** [comment]
are you on master?  someone submitted https://github.com/openai/gpt-2/pull/28 to fix a similar issue

**Comment by studiosi** [comment]
I just cloned yesterday from master, yes.

**Comment by studiosi** [comment]
Update: in order for it to work, I opened it with VS Code and resaved it using Windows 1252 encoding, then the software was able to load it.
