### ISSUE TITLE
Abstractive summarization

### ISSUE THREAD

**Issue by bertagknowles** [openai/gpt-2#33]
How can I create an abstractive summary of a text document?

**Comment by WuTheFWasThat** [comment]
See paper for details!

**Comment by bertagknowles** [comment]
According to the paper "To induce summarization behavior we add the text TL;DR: ". Where do we add the document text to be summarized? Is it after this command at the prompt - "python3 src/interactive_conditional_samples.py " ?

**Comment by WuTheFWasThat** [comment]
unfortunately I'm not sure if you can add newlines when using interactive_conditional_samples - but normally it would be 

```
[article]
TL;DR:
```

**Comment by HaleTom** [comment]
For other googlers, section 3.6 of [the paper](https://d4mucfpksywv.cloudfront.net/better-language-models/language-models.pdf) relates to this, but the method is described in very high-level terms.

Also look at [`interactive_conditional_samples.py`](https://github.com/openai/gpt-2/blob/master/src/interactive_conditional_samples.py)

**Comment by WuTheFWasThat** [comment]
@HaleTom if you have specific questions about the methodology feel free to ask!  it really is very simple

**Comment by bertagknowles** [comment]
It seems the summary is based on the context of trained data and not the document I present to it. The model forms opinions on the global news and entertainment data and not on specific topic that I want.

**Comment by WuTheFWasThat** [comment]
I would guess that's probably a bug in your code

**Comment by bertagknowles** [comment]
I got my answer on quora that the summary is more imaginative than abstractive or extractive. See below:
--------------
_Example 9. Summarization

Input:

norway delivered a diplomatic protest to russia on monday after three norwegian fisheries research expeditions were barred from russian waters . the norwegian research ships were to continue an annual program of charting fish resources shared by the two countries in the barents sea region TL;DR:

Output:

Norwegian fishing boat was caught in a fishing accident in the Barents Sea.

The Norwegian fishing vessel was caught in a fishing accident in the barents sea.

Norway's Fisheries Research Program (FPR) was suspended on Tuesday after a Norwegian ship carrying a Norwegian fishing boat was caught in a fishing accident in the barents sea region TL;DR: Norway's Fisheries Research Program was suspended on Tuesday after a Norwegian ship carrying a Norwegian fishing boat was caught in a fishing accident in the barents sea region.

The Norwegian fishing vessel was caught in a fishing accident in the barents sea.

The Norwegian fishing vessel was caught in a fishing accident in the barents sea.

The Norwegian fishing vessel was caught in a fishing accident in the barents sea.

Notes. More on the imaginative side than abstractive or extractive. Again could be because of low model capacity , though even GPT-2 didn’t do well in summarization compared to supervised model performances_
------------------

**Comment by ckpm** [comment]
I don't think the summarization mode is implemented in the src

**Comment by federicosan** [comment]
Maybe the model is only trained to content generation, not text summarization.

**Comment by mwizasimbeye11** [comment]
This worked for me `python src/interactive_conditional_samples.py --nsamples=3 --length=100 --temperature=1 `

Then added [article] TL;DR:
