### ISSUE TITLE
My CPU doesn't support Tensorflow AVX instructions 

### ISSUE THREAD

**Issue by bertagknowles** [openai/gpt-2#34]
I was able to install all the requirements. However while generating samples, getting the following error. I have an Intel i3 First gen Processor and running Ubuntu 18.

_2019-02-16 03:12:49.453982: F tensorflow/core/platform/cpu_feature_guard.cc:37] The TensorFlow library was compiled to use AVX instructions, but these aren't available on your machine.
Aborted (core dumped)_

I then installed Tensorflow 1.5 (pip3 install tensorflow==1.5). The sample was generated, however another warning popped up as shown below. Will this affect the quality? Do I need to compile TensorFlow on my system?

_2019-02-16 03:22:19.785441: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2_

**Comment by studiosi** [comment]
This piece of [documentation ](https://docs.microsoft.com/en-us/windows/desktop/win7appqual/enable-windows-7-support-for-intel-avx) by Microsoft may help you with AVX, at least if you are using Windows 7.

**Comment by bertagknowles** [comment]
Thx for the suggestions. Can I use a precompiled wheel from https://github.com/mind/wheels ?

**Comment by studiosi** [comment]
I suppose you can, I don't see any reason why you wouldn't.

**Comment by miweru** [comment]
The mind wheels may not work, because they are a bit old. Maybe one of these is useful: https://github.com/yaroslavvb/tensorflow-community-wheels/issues

**Comment by twallace12** [comment]
I ran into the exact same problem with Ubuntu Server running on top of Hyper-V. I'm going to switch to running on Ubuntu Server on hardware to see if it makes a difference.

**Comment by twallace12** [comment]
Switched to Ubuntu Server running on bare hardware (Dell R710) and got this message: 2019-02-16 17:07:14.788642: F tensorflow/core/platform/cpu_feature_guard.cc:37] The TensorFlow library was compiled to use AVX instructions, but these aren't available on your machine.

Anyone found a workaround?

**Comment by twallace12** [comment]
OK -- switched to an Ubuntu Server virtual machine on Hyper-V on Windows 10 running on an Intel i7 -- everything is working and producing fascinating text. :)

**Comment by 4R7I5T** [comment]
I get this same error but it ends up working if I wait it out

**Comment by bhack** [comment]
https://github.com/tensorflow/tensorflow/issues/25519#issuecomment-460819834

**Comment by bertagknowles** [comment]
> I get this same error but it ends up working if I wait it out

Yes, even on my virtual machine, the error is there but after some time the output is shown. Just want to know if resolving this warning will affect the quality of the output. I don't know how to compile the tensorflow binary and which flags to use.

**Comment by studiosi** [comment]
It should not affect the quality, but only the speed. Those instructions are optimizations to run faster floating point operations.

**Comment by twallace12** [comment]
Has anyone figured out how to prompt the system with sentences, as in the examples?

**Comment by philippHRO** [comment]
> 
> 
> Has anyone figured out how to prompt the system with sentences, as in the examples?

This is off topic, but yeah. if you start the model in conditional mode, it will give you a prompt to enter your sentences.
`python3 src/interactive_conditional_samples.py --top_k 40`

**Comment by WuTheFWasThat** [comment]
closing, feel free to reopen if there's an actual issue to resolve

**Comment by foobar167** [comment]
Try Anaconda. It has TensorFlow distribution for old CPU.

**Comment by nhogan5** [comment]
The CPU its self also needs to support the instructions sets. My Legacy Intel(R) Xeon(R) CPU E5520 in my r710 does not. Stumbled upon this: https://www.tensorflow.org/install/pip#hardware-requirements The link takes you to compatible CPUs.
