### ISSUE TITLE
模型下载失败

### ISSUE THREAD

**Issue by edbea** [openai/gpt-2#36]
你好。
我是python3的环境，可是gsutil requires python 2.7。除了通过gsutil，请问有没有其他的下载链接方式呢？谢谢。如果可以，是否可以发送到我邮箱：1224070840@qq.com。谢谢

**Comment by WuTheFWasThat** [comment]
duplicate of https://github.com/openai/gpt-2/issues/18

**Comment by edbea** [comment]
0     0    0     0    0     0      0      0 --:--:--  0:01:15 --:--:--     0curl: (7) Failed to connect to drive.google.com port 443: Operation timed out
