### ISSUE TITLE
Is it fine to implemente gpt2 on Pytorch?

### ISSUE THREAD

**Issue by graykode** [openai/gpt-2#37]
Thanks for the awesome work! 👍 
Can I try to implement gpt2 on Pytorch?
Of course, I'll write down the sources of the papers and codes.

**Comment by studiosi** [comment]
I would wait until there is a license in place, currently there is an open issue for the licensing of this code: #10

**Comment by WuTheFWasThat** [comment]
yep, we will put a license soon (next week), sorry for the delay!

**Comment by graykode** [comment]
@WuTheFWasThat Is it fine my Pytorch Code to be **Open** which is just convert tensorflow to **Pytorch**?
