### ISSUE TITLE
模型依然没法下载

### ISSUE THREAD

**Issue by edbea** [openai/gpt-2#43]
0     0    0     0    0     0      0      0 --:--:--  0:01:15 --:--:--     0curl: (7) Failed to connect to drive.google.com port 443: Operation timed out

你好，我们（中国）这里还是没法下载。真心请把模型文件放到一个网盘。或者是否可以直接把模型发送到我的邮箱：1224070840@qq.com

感谢感谢啦。

**Comment by WuTheFWasThat** [comment]
there should be no use of drive.google.com, i think you're using an unsupported branch.  try master, which no longer uses gsutil
