### ISSUE TITLE
How to download on windows?

### ISSUE THREAD

**Issue by FloridaPete** [openai/gpt-2#45]
I'm using Windows 10, 64x. Could someone please explain to a novice how to download this?
1) Following the instructions, I downloaded gsutil and started a new configuration. Run:
sh download_model.sh 117M
But receive error:
download_model.sh: download_model.sh: No such file or directory

2) Tried both:
gsutil cp -r dir gs://gpt-2/models/117M
gsutil cp -r dir gs://gpt-2/models/models
But receive error:
AccessDeniedException: 403 [my gmail] does not have storage.objects.list access to gpt-2.

3) Tried the solution from loretoparisi at
https://github.com/loretoparisi/gpt-2/blob/master/download_model.sh
But I think I'm doing something wrong here. I downloaded Curl and Grep, then created a .bat file in Notepad++ with his script. Executed the file, but it only opens and closes.

Any help would be greatly appreciated.
Thanks,
Pete

**Comment by anmar01** [comment]
Same issue here

**Comment by mrene** [comment]
All the script does is download the following files into `./models/117M` (starting from the repo's directory), you can always download them manually if you have trouble executing them.

https://storage.googleapis.com/gpt-2/models/117M/checkpoint
https://storage.googleapis.com/gpt-2/models/117M/encoder.json
https://storage.googleapis.com/gpt-2/models/117M/hparams.json
https://storage.googleapis.com/gpt-2/models/117M/model.ckpt.data-00000-of-00001
https://storage.googleapis.com/gpt-2/models/117M/model.ckpt.index
https://storage.googleapis.com/gpt-2/models/117M/model.ckpt.meta
https://storage.googleapis.com/gpt-2/models/117M/vocab.bpe

**Comment by FloridaPete** [comment]
Oh. Ha! Thanks for clarifying.

**Comment by dadhichi1** [comment]
i used gitbash to download with sh commands

**Comment by WuTheFWasThat** [comment]
latest code doesn't use gsutil anymore!

**Comment by nsikanjicmarinexchange** [comment]
Hi, 
is this resolved as I have the same issue? 
I am just starting with this topic so apologizes if it is a trivial question :)
Any help is much appreciated!
