### ISSUE TITLE
Wrong Scaling in multiattention?

### ISSUE THREAD

**Issue by unrealwill** [openai/gpt-2#49]
Hello, 

Not quite sure if this is intended or not, 
https://github.com/openai/gpt-2/blob/master/src/model.py#L94

You are scaling by rsqrt(dim value) where as it is usual to scale by rsqrt( dim key ).
Is this a typo or does it work better?

Thanks

**Comment by WuTheFWasThat** [comment]
ah, in this case they are the same, so it doesn't matter
