### ISSUE TITLE
Window size error when trying to sample

### ISSUE THREAD

**Issue by janelleshane** [openai/gpt-2#5]
I'm trying to sample from 117M using the following commands:

` python3 src/generate_unconditional_samples.py`
` python3 src/generate_unconditional_samples.py | tee samples `
` python3 src/interactive_conditional_samples.py `

And I get the following error: 

>   File "src/interactive_conditional_samples.py", line 34
>    raise ValueError(f"can't get samples longer than window size: {hparams.n_ctx}")
>                                                                                                                                        ^
> SyntaxError: invalid syntax

**Comment by minimaxir** [comment]
Are you using Python 3.6? #6

**Comment by janelleshane** [comment]
I'm using Python 3.5.2

**Comment by ilopezfr** [comment]
Same here. Including when adding the flags: 
`python3 src/generate_unconditional_samples.py --top_k 40 --temperature 0.7 | tee samples`

```
  File "src/generate_unconditional_samples.py", line 31
    raise ValueError(f"can't get samples longer than window size: {hparams.n_ctx}")
                                                                                 ^
SyntaxError: invalid syntax
```

**Comment by WuTheFWasThat** [comment]
pushed a fix, try again!  @janelleshane

**Comment by drizzt00s** [comment]
where is the fix?
