### ISSUE TITLE
[PROPOSAL] Allow remote testing of larger models 

### ISSUE THREAD

**Issue by RobertoMalatesta** [openai/gpt-2#53]
Your paper and this implementation could mark a significant evolution in UMLs.
Especially (for what I'm concerned) in CoQa & translation.
It would be nice to kick the tires of the full model even remotely, without having direct access to it.
Would you consider setting up -say- a MQTT server with some channels to be able to interact with a couple of functionalities?
Abuse of this service could be moderated by simply pruning out suspicious requests &&/|| by  sending authorization to validated mail.

--R

**Comment by WuTheFWasThat** [comment]
Thanks - we're considering possibilities along these lines, but no promises.  This repository isn't the place to discuss this, unfortunately
