### ISSUE TITLE
Integrate a training feature to pass JSON markup convo data 

### ISSUE THREAD

**Issue by 4R7I5T** [openai/gpt-2#54]
Other alternatives to this software have allowed such a system to exist problem free, cakechat by Replika.ai for example; allows and encourages people to check out the 40GB reddit corpus you guys build GPT-2 from. I was getting highly similar results with altering their token model and marking up the JSON with emotion compared to what I am seeing with your currently released solution. 

**Examples of things more dangerous than your software that turned out safer than imagined...:**

Example #1: Fusor.net provides detailed instructions on how to build a nuclear fusion reactor, 12 year olds in south america have even made them. Yet Bogota hasn't become Chernobyl. 

Example #2: 3D printed weapons have been around for years and actually are far more safe / less accessible than normal weapons.  Nobody has ever been harmed by one. 

Example #3: The early days of Bitcoin, although they were accompanied by some awful things - didn't do anything as bad as what the Sinaloa cartel managed under El Chapo daily for decades unchecked. 

I'll protest this until I get my own copy of this software. It's a human right for you guys to release your full, open and honest production software instead of choose profit and proprietary.

**Comment by WuTheFWasThat** [comment]
Thanks for your examples.  We're completely open to the idea that our software isn't dangerous, and different people within the org have differing views.  However, we've decided to proceed cautiously and to start a conversation around these topics.  

I don't think there's an issue specific to this repository so i'm closing this
