### ISSUE TITLE
Which python should be used? 3.7.2 catches exception

### ISSUE THREAD

**Issue by salux-x** [openai/gpt-2#55]
Using 3.7.2 on any tutorial cmd

> python3 src/interactive_conditional_samples.py --top_k 40
> /usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.6 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.7
>   return f(*args, **kwds)
> 2019-02-19 17:51:24.116332: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
> Traceback (most recent call last):
>   File "src/interactive_conditional_samples.py", line 68, in <module>
>     fire.Fire(interact_model)
>   File "/usr/local/lib/python3.7/site-packages/fire/core.py", line 127, in Fire
>     component_trace = _Fire(component, args, context, name)
>   File "/usr/local/lib/python3.7/site-packages/fire/core.py", line 366, in _Fire
>     component, remaining_args)
>   File "/usr/local/lib/python3.7/site-packages/fire/core.py", line 542, in _CallCallable
>     result = fn(*varargs, **kwargs)
>   File "src/interactive_conditional_samples.py", line 42, in interact_model
>     temperature=temperature, top_k=top_k
>   File "/Users/steinmacht/gpt-2/src/sample.py", line 76, in sample_sequence
>     back_prop=False,
>   File "/usr/local/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3291, in while_loop
>     return_same_structure)
>   File "/usr/local/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3004, in BuildLoop
>     pred, body, original_loop_vars, loop_vars, shape_invariants)
>   File "/usr/local/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2924, in _BuildLoop
>     c = ops.convert_to_tensor(pred(*packed_vars))
>   File "/usr/local/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3259, in <lambda>
>     math_ops.logical_and(i < maximum_iterations, orig_cond(*lv)))
>   File "/usr/local/lib/python3.7/site-packages/tensorflow/python/ops/gen_math_ops.py", line 4365, in logical_and
>     "LogicalAnd", x=x, y=y, name=name)
>   File "/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 510, in _apply_op_helper
>     preferred_dtype=default_dtype)
>   File "/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1146, in internal_convert_to_tensor
>     ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
>   File "/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py", line 229, in _constant_tensor_conversion_function
>     return constant(v, dtype=dtype, name=name)
>   File "/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py", line 208, in constant
>     value, dtype=dtype, shape=shape, verify_shape=verify_shape))
>   File "/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/tensor_util.py", line 542, in make_tensor_proto
>     append_fn(tensor_proto, proto_values)
>   File "tensorflow/python/framework/fast_tensor_util.pyx", line 134, in tensorflow.python.framework.fast_tensor_util.AppendBoolArrayToTensorProto
>   File "/usr/local/lib/python3.7/site-packages/numpy/lib/type_check.py", line 547, in asscalar
>     return a.item()
> UnboundLocalError: local variable 'a' referenced before assignmen

**Comment by philippHRO** [comment]
3.6.8

**Comment by WuTheFWasThat** [comment]
I belive tensorflow doesn't support 3.7 in general
