### ISSUE TITLE
Requirements on Arch Linux 

### ISSUE THREAD

**Issue by yogaskung** [openai/gpt-2#59]
These who use archlinux should not follow the instructions but try to
`pacman -S python-regex tensorflow`
`aurman -S python-fire`
After uninstall everything that will be install by pacman.
I did piping install the sample did nothing and exit

**Comment by yogaskung** [comment]
https://bbs.archlinux.org/viewtopic.php?id=240268
#55

**Comment by chrisjbillington** [comment]
Following the instructions as written, using a virtualenv or conda env would totally work on Arch. So people following that will not go wrong: it does not say to use pip at the system level and clobber your system packages like the thread you linked starts out doing. Anyway, arch users should know not to install things at the system level without pacman unless they really know what they are doing. This is fundamental to using Arch: projects should not require special 'Arch install' instructions.

It's a luxury in Arch that we can usually install up-to-date dependencies with the system package manager and an AUR helper and run projects like this without having to make a virtualenv or spew random untracked files throughout the filesystem. But there are very few distros where this is the case, so I understand not wanting to hint that anyone should use their system package manager in the instructions.

Then again the OP of the thread you linked seems to have not known this, so maybe I am wrong about this being assumed knowledge for anyone using Arch.
