### ISSUE TITLE
Generate conditional output based on input keywords

### ISSUE THREAD

**Issue by barnebyte** [openai/gpt-2#62]
I think it would be nice if it would be possible to generate an output sentence based on input keywords, where the lenght of the sentence, or the input/output words ratio could be fine tuned. In this way we could create a higher system (motive) which could use this model to generate a guided conversation.

**Comment by WuTheFWasThat** [comment]
I'm not sure I entirely understand the proposal, but it doesn't sound core to the functionality of this release (correct me if I'm wrong).  It sounds like it may be an easy modification to the code, so feel free to fork, but I'd prefer not to add anything to the main codebase

**Comment by ragna211** [comment]
I find this project really interesting. But how to give our own customised input?
