### ISSUE TITLE
After These Messages We'll Be Right Back

### ISSUE THREAD

**Issue by Kreuzader** [openai/gpt-2#64]
Very minor and semi-amusing, but noticed gpt-2 with the 117M model will generate "Advertisements" as a string in isolation on a line, so I'm guessing the training data has that somewhere that could be scrubbed whenever is convenient.

The implications of AIs accidentally learning to value commercial interruption is left as an exercise for the reader :)

**Comment by WuTheFWasThat** [comment]
yeah, we're aware of the problem, as well as many other problems with the training data, some more pernicious than others.  won't be fixed for this release though
