### ISSUE TITLE
ModuleNotFoundError: No module named 'src'

### ISSUE THREAD

**Issue by minimaxir** [openai/gpt-2#7]
```
maxwoolf$ sudo python3 src/generate_unconditional_samples.py
Traceback (most recent call last):
  File "src/generate_unconditional_samples.py", line 9, in <module>
    from src import model, sample, encoder
ModuleNotFoundError: No module named 'src'
```
Python can't import from a subfolder unless it's on the Python path.

**Comment by WuTheFWasThat** [comment]
works for me but pull request welcome!

**Comment by reisner** [comment]
@minimaxir `export PYTHONPATH=$PYTHONPATH:.`

**Comment by zucimalar** [comment]
If I have run mark in pytest it through error like this(E ModuleNotFoundError: No module named 'src').how will fixe that error.please give me any solution
