### ISSUE TITLE
No module named 'fire' issue 

### ISSUE THREAD

**Issue by Tristan1551** [openai/gpt-2#72]
Hi, 
I wanted to try to generate some text but I have an issue while trying to use commands for text generation, the console tells me that no module named fire has been found. I have installed fire 0.1.3 but there is still an error 

tristan@DESKTOP-7AFO391:~/gpt-2$ python3 src/generate_unconditional_samples.py --top_k=1
Traceback (most recent call last):
  File "src/generate_unconditional_samples.py", line 3, in <module>
    import fire
ModuleNotFoundError: No module named 'fire'

any ideas what i could have done wrong ? 
I'm using windows 10 and the ubuntu console 

Thank you

**Comment by Tristan1551** [comment]
i've actually find an answer i had to install fire with pip3 and not pip

**Comment by aaquibzama** [comment]
I was trying with pip3 all along. Your comment gave me an idea to try it with pip. Surprisingly, it worked :)

**Comment by ManuelitoMartinez** [comment]
I'm having the same problem. Already tried pip and pip3 but didn't worked.

**Comment by nopenopenope** [comment]
Same!

**Comment by parz3val** [comment]
I am managing my dependencies with Poetry and I am still getting the same error.

**Comment by Cr3AD** [comment]
Same issue with python3.7.3 and pip3 18.1, tried with pip also
