### ISSUE TITLE
Getting all exclamation marks on Windows

### ISSUE THREAD

**Issue by enlightdm** [openai/gpt-2#73]
Once model is downloaded, I tried the interactive python and does not matter what I write, the output is
SAMPLE 1 ===
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!
And 3 or 4 lines or exclamation marks.
This happens also with samples.

**Comment by enlightdm** [comment]
Looks like this only happens with TensorFlow on GPU.
Switched to CPU and it worked.

**Comment by danvdragos** [comment]
I have the same issue
![image](https://user-images.githubusercontent.com/13160957/53526379-abc4b900-3aec-11e9-83d2-a5787ff01737.png)

Windows 10, tensorflow 1.12, python 3.7, CUDA 10.0

**Comment by kevinling0218** [comment]
Save issue here
