### ISSUE TITLE
Port model download script to python

### ISSUE THREAD

**Issue by WuTheFWasThat** [openai/gpt-2#74]

**Comment by webproduktion01** [comment]
Converted your bash script to python if you want it. 
[branch](https://github.com/webproduktion01/gpt-2/tree/PythonDownloadScript) 
[Commit](https://github.com/webproduktion01/gpt-2/commit/c573da092a8603a10b00a83e9af29c21fcdd4aba)

**Comment by WuTheFWasThat** [comment]
@webproduktion01  thanks!  can we use a library like tqdm instead of custom progress bar code?  if you submit a pull request, happy to accept it!

**Comment by webproduktion01** [comment]
[replaced the progressbar with tqdm](https://github.com/webproduktion01/gpt-2/commit/fac0a9516b2a3d98f61154e1784930e980c9bace) I'm not sure however how to submit a pull request from the cloned repo however to yours. I need to learn that. You have my permission to port over the code if you want.

**Comment by webproduktion01** [comment]
figured out. The pull request =  #89
