### ISSUE TITLE
Rephrasing a sentence

### ISSUE THREAD

**Issue by bertagknowles** [openai/gpt-2#75]
Can this model rephrase a given sentence or even paraphrase? At the prompt, I tried to give a sample such as:
Symptoms of influenza include fever and nasal congestion = A stuffy nose and elevated temperature are signs you may have the flu.
Giraffes like Acacia leaves and hay, and they can consume 75 pounds of food a day. = 

But the sample returned something completely different.

**Comment by WuTheFWasThat** [comment]
it might be able to, to some extent.  you should use more examples in the context (as many as possible), and also truncate to top_k = 1

**Comment by SandeepBhutani** [comment]
Hi @bertagknowles : I am also looking for similar solution. Were you able to make it work for paraphrasing?

**Comment by devajithvs** [comment]
See this: https://arxiv.org/abs/1911.09661

**Comment by MastafaF** [comment]
Hi @devajithvs , did they open source their training procedure and/or their model?
