### ISSUE TITLE
How to cite the paper

### ISSUE THREAD

**Issue by ferreirafabio** [openai/gpt-2#79]
How should the paper be cited? I could not find bibtex entries on the internet. Thank you

**Comment by WuTheFWasThat** [comment]
Please use this for now!

@article{radford2019language,
  title={Language Models are Unsupervised Multitask Learners},
  author={Radford, Alec and Wu, Jeff and Child, Rewon and Luan, David and Amodei, Dario and Sutskever, Ilya},
  year={2019}
}
