### ISSUE TITLE
Windows installation

### ISSUE THREAD

**Issue by phenoty** [openai/gpt-2#83]
Hi. Found this software through a game. This could help a lot with the roleplay posts. A game changer! Unfortunately, total noob here. So, I was wondering if someone could guide me through a detailed windows 8 installation?

**Comment by ZF7724** [comment]
Download VMware! or use Ubuntu bootable USB stick.

https://tutorials.ubuntu.com/tutorial/tutorial-create-a-usb-stick-on-windows#0

Then just open terminal and follow steps on https://github.com/openai/gpt-2

**Comment by WuTheFWasThat** [comment]
you can also just run on windows directly, i think.  just need python and git (and git bash), i believe!
