### ISSUE TITLE
How can I train your model on my own text corpus?

### ISSUE THREAD

**Issue by deemeetree** [openai/gpt-2#84]
I know that you trained your model on a corpus of news texts. I would like to train it on my own set of documents. I'm not looking for precision, rather for poetry. Could you please tell me how I could create my own training set and reactivate this model?

**Comment by benonilearns** [comment]
You can't because they haven't released it. They just released a pretrained model on 40GB of webtext.

**Comment by WuTheFWasThat** [comment]
dup of https://github.com/openai/gpt-2/issues/19, see my comment there!

**Comment by ak9250** [comment]
I made a colab repo where you can train on your own set of text here, let me know if you have any questions https://github.com/ak9250/gpt-2-colab

**Comment by CaptainValor** [comment]
@deemeetree I'm using a modified fork of @ak9250's Google Colab notebook. It works! Have included code for building a single huge English training text file based on Project Gutenberg (books) or Access to Insight (Dharma texts). ATI seems to overfit quite rapidly, but a 99mb subset of Gutenberg came out quite convincing after only 4 hours of training. YMMV https://github.com/CaptainValor/gpt-2-colab

See this thread for other options: https://github.com/openai/gpt-2/issues/19
