### ISSUE TITLE
Is it possible to edit the code based on this project to train from scratch?

### ISSUE THREAD

**Issue by guotong1988** [openai/gpt-2#86]
Is it possible? To achieve maybe 90% of the experiment result in the paper.
Thank you very much!

**Comment by WuTheFWasThat** [comment]
no, sorry!!  we haven't released the training code as of now

**Comment by guotong1988** [comment]
How about gpt-1?
https://github.com/openai/finetune-transformer-lm/issues/42
@WuTheFWasThat Thank you!
