### ISSUE TITLE
Help doing transfer learning to generate spanish-language text?

### ISSUE THREAD

**Issue by maraoz** [openai/gpt-2#9]
Hi! Amazing results :open_mouth: 
I know this is an open-ended and lazy question, but I'd appreciate if you could give me some pointers into how to re-train the model with additional text in another language (e.g spanish). I already have a small (6 MB) dataset in spanish, and I'm not very well versed in ML but I'm curious about playing with your model. 
Thanks! I'll be sure to report results back if I somehow figure it out :)

**Comment by WuTheFWasThat** [comment]
thanks!  this is probably not the right repo to start with.  maybe https://github.com/tensorflow/tensor2tensor/, not sure

**Comment by ilopezfr** [comment]
@maraoz were you able to re-train the model to generate Spanish text?
