### ISSUE TITLE
error downloading model using "python download_model.py 117M"

### ISSUE THREAD

**Issue by zwumdd** [openai/gpt-2#90]
got this permission error:

<Error>
<Code>AccessDenied</Code>
<Message>Access denied.</Message>
<Details>
Anonymous caller does not have storage.objects.get access to gpt-2/117M/encoder.json.
</Details>
</Error>

**Comment by Valen558** [comment]
the same, got all files in the models directory filled with
`<?xml version='1.0' encoding='UTF-8'?><Error><Code>AccessDenied</Code><Message>Access denied.</Message><Details>Anonymous caller does not have storage.objects.get access to gpt-2/models\117M/encoder.json.</Details></Error>`

**Comment by Valen558** [comment]
The issue was encountered on Windows 10. 
Likely has to do with the downloader adding an extra slash to the url.
Downloaded manually all the files to the gpt-2\models\117M directory:

https://storage.googleapis.com/gpt-2/models/117M/checkpoint
https://storage.googleapis.com/gpt-2/models/117M/encoder.json
https://storage.googleapis.com/gpt-2/models/117M/hparams.json
https://storage.googleapis.com/gpt-2/models/117M/model.ckpt.data-00000-of-00001
https://storage.googleapis.com/gpt-2/models/117M/model.ckpt.index
https://storage.googleapis.com/gpt-2/models/117M/model.ckpt.meta
https://storage.googleapis.com/gpt-2/models/117M/vocab.bpe

**Comment by jschvartz** [comment]
I do not have this problem using win10 [10.0.17134 N/A version 17134] , using Python 3.6.2.
Nor did I with Docker version 18.03.0-ce, build 0520e24302  (same windows platform).
Nice work, though a few checks in the script would be welcome.

**Comment by chrothenbach** [comment]
> The issue was encountered on Windows 10.
> Likely has to do with the downloader adding an extra slash to the url.
> Downloaded manually all the files to the gpt-2\models\117M directory:
> 
> https://storage.googleapis.com/gpt-2/models/117M/checkpoint
> https://storage.googleapis.com/gpt-2/models/117M/encoder.json
> https://storage.googleapis.com/gpt-2/models/117M/hparams.json
> https://storage.googleapis.com/gpt-2/models/117M/model.ckpt.data-00000-of-00001
> https://storage.googleapis.com/gpt-2/models/117M/model.ckpt.index
> https://storage.googleapis.com/gpt-2/models/117M/model.ckpt.meta
> https://storage.googleapis.com/gpt-2/models/117M/vocab.bpe

Thank you for posting these.

**Comment by zwumdd** [comment]
The issue is on Windows. I replaced "\" with "/" in the url in the download py script and it fixed the issue. Please fix the official download script. Thanks.

**Comment by chrothenbach** [comment]
> The issue is on Windows. I replaced "" with "/" in the url in the download py script and it fixed the issue. Please fix the official download script. Thanks.
Thanks for pointing that out. I think what was happening is that when os.makedirs is called it adds the '\' (backslash) terminator to subdir, which Python in Windows does not interpret properly.  


I fixed it by adding a subdir.replace line as shown below:

```
subdir = os.path.join('models', model)
if not os.path.exists(subdir):
    os.makedirs(subdir)
subdir = subdir.replace('\\','/')
```

**Comment by WuTheFWasThat** [comment]
thanks @chrothenbach, fixed in 86378284e119d09bd2b6e449d9bac52c9b821db7

**Comment by danhab99** [comment]
Still having this issue. I clicked on this link https://storage.googleapis.com/gpt-2/models/117M/checkpoint with my browser and I got the same error message

**Comment by JXCrazy** [comment]
Then i have open these website, i found that the website can't be opened, the display is invalid.
