### ISSUE TITLE
Well thought out reasoning of releasing world-modifying tools

### ISSUE THREAD

**Issue by bladedsupernova** [openai/gpt-2#95]
I thought this out well.

AGI, ASI, and tools that can instantly change Earth in days (nanobots), can not be handed to ALL humans. [Some] humans are disabled and are not fit. In fact, if [some] humans even [see, not hear] on the news an AGI android talking to us, they may send nukes off. Generating huge curated text may prove to readers some ideas, and readers often trust it when they read Trump did X. When it comes to others ideas to prove to the reader, more tangible hand-on ideas, those are harder - and if they can be proven then they may be indeed true. Like how to make Cryonics work. Humans can already write up walls of text way better.

There's a catch. The more friends you tell, the more progress you get. You must verify them as stable. The more people you tell, the more likely a disabled man will hear about the powerful tool. We are not at this stage yet. If it were big nanobot organisms then it would be tight because they can morph and eat Earth. ASI. Too few people in on it though, and the gov may take you.

My answer is: Release how GPT2 works.

**Comment by WuTheFWasThat** [comment]
thanks for your thoughts.  we have released what we know about how it works!
