### ISSUE TITLE
Input size is restricted in 2 ways

### ISSUE THREAD

**Issue by bladedsupernova** [openai/gpt-2#97]
When I enter the small model a wall of text bigger than 396 words, it always errors. How can I feed it a big page?

Also, if my input isn't 1 wall of text, it thinks my input in ex. 8 queries, and I have to exit my program or else it goes through each paragraph one by one.

**Comment by WuTheFWasThat** [comment]
yeah the interactive sampling script currently doesn't take newlines, i think

**Comment by mark-otaris** [comment]
You can insert newlines with C-v C-j, thanks to `input`’s readline support.

**Comment by bladedsupernova** [comment]
Entering the below as a model prompt does not work...it makes it run 3 times. Where in the code do i go? Explain...

The dog was at the park.

C-v C-j

But it was also at home.

**Comment by mark-otaris** [comment]
You can't paste it. But you can press Ctrl+V Ctrl+J after entering the first line.

**Comment by bladedsupernova** [comment]
Not working.

When I type in my 2-paragraph prompt, do I type just the first or both paragraphs?

Next, do I hold down all 4 keys after or before I hit 'enter'?
